### ISSUE TITLE
trouble with ./configure on Linux Mint 17.1 64-bit

### ISSUE THREAD

**Issue by pasha23** [feeley/gambit#107]
I pulled the latest with git and attempted to run configure.

I am not too familiar with the details of autoconf, etc. but configure returned error 77.

I am not sure how to fix this.

Script started on Mon 02 Mar 2015 10:29:35 AM PST
$ uname -a
Linux ThinkCentre-M90p 3.13.0-37-generic #64-Ubuntu SMP Mon Sep 22 21:28:38 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.8/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 4.8.2-19ubuntu1' --with-bugurl=file:///usr/share/doc/gcc-4.8/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.8 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.8 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-libmudflap --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.8-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 4.8.2 (Ubuntu 4.8.2-19ubuntu1) 
$ bash configure
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
checking for gcc... gcc
checking whether the C compiler works... no
configure: error: in `/home/pasha/gambit':
configure: error: C compiler cannot create executables
See `config.log' for more details
$ cat config.log
This file contains any messages produced by compilers while
running configure, to aid debugging if configure makes a mistake.

It was created by Gambit-C configure v4.7.4, which was
generated by GNU Autoconf 2.69.  Invocation command line was

  $ configure 

## --------- ##

hostname = ThinkCentre-M90p
uname -m = x86_64
uname -r = 3.13.0-37-generic
uname -s = Linux
uname -v = #64-Ubuntu SMP Mon Sep 22 21:28:38 UTC 2014

/usr/bin/uname -p = unknown
/bin/uname -X     = unknown

/bin/arch              = unknown
/usr/bin/arch -k       = unknown
/usr/convex/getsysinfo = unknown
/usr/bin/hostinfo      = unknown
/bin/machine           = unknown
/usr/bin/oslevel       = unknown
/bin/universe          = unknown

PATH: /opt/gcc-arm-none-eabi-4_9-2014q4/bin
PATH: /usr/local/sbin
PATH: /usr/local/bin
PATH: /usr/sbin
PATH: /usr/bin
PATH: /sbin
PATH: /bin
PATH: /usr/games
PATH: /usr/local/games

## ----------- ##

configure:2825: checking build system type
configure:2839: result: x86_64-unknown-linux-gnu
configure:2859: checking host system type
configure:2872: result: x86_64-unknown-linux-gnu
configure:2892: checking target system type
configure:2905: result: x86_64-unknown-linux-gnu
configure:3143: checking for gcc
configure:3159: found /usr/bin/gcc
configure:3170: result: gcc
configure:3399: checking for C compiler version
configure:3408: gcc --version >&5
gcc (Ubuntu 4.8.2-19ubuntu1) 4.8.2
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

configure:3419: $? = 0
configure:3408: gcc -v >&5
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.8/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 4.8.2-19ubuntu1' --with-bugurl=file:///usr/share/doc/gcc-4.8/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.8 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.8 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-libmudflap --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.8-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 4.8.2 (Ubuntu 4.8.2-19ubuntu1) 
configure:3419: $? = 0
configure:3408: gcc -V >&5
gcc: error: unrecognized command line option '-V'
gcc: fatal error: no input files
compilation terminated.
configure:3419: $? = 4
configure:3408: gcc -qversion >&5
gcc: error: unrecognized command line option '-qversion'
gcc: fatal error: no input files
compilation terminated.
configure:3419: $? = 4
configure:3439: checking whether the C compiler works
configure:3461: gcc    conftest.c  >&5
/usr/bin/ld: cannot find crt1.o: No such file or directory
/usr/bin/ld: cannot find crti.o: No such file or directory
/usr/bin/ld: cannot find -lc
/usr/bin/ld: cannot find crtn.o: No such file or directory
collect2: error: ld returned 1 exit status
configure:3465: $? = 1
configure:3503: result: no
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "Gambit-C"
| #define PACKAGE_TARNAME "gambc-v4_7_4"
| #define PACKAGE_VERSION "v4.7.4"
| #define PACKAGE_STRING "Gambit-C v4.7.4"
| #define PACKAGE_BUGREPORT "gambit@iro.umontreal.ca"
| #define PACKAGE_URL ""
| /* end confdefs.h.  */
| 
| int
| main ()
| {
| 
|   ;
|   return 0;
| }
configure:3508: error: in `/home/pasha/gambit':
configure:3510: error: C compiler cannot create executables
See `config.log' for more details

## ---------------- ##

ac_cv_build=x86_64-unknown-linux-gnu
ac_cv_env_CCC_set=
ac_cv_env_CCC_value=
ac_cv_env_CC_set=
ac_cv_env_CC_value=
ac_cv_env_CFLAGS_set=
ac_cv_env_CFLAGS_value=
ac_cv_env_CPPFLAGS_set=
ac_cv_env_CPPFLAGS_value=
ac_cv_env_CPP_set=
ac_cv_env_CPP_value=
ac_cv_env_CXXCPP_set=
ac_cv_env_CXXCPP_value=
ac_cv_env_CXXFLAGS_set=
ac_cv_env_CXXFLAGS_value=
ac_cv_env_CXX_set=
ac_cv_env_CXX_value=
ac_cv_env_LDFLAGS_set=
ac_cv_env_LDFLAGS_value=
ac_cv_env_LIBS_set=
ac_cv_env_LIBS_value=
ac_cv_env_XMKMF_set=
ac_cv_env_XMKMF_value=
ac_cv_env_build_alias_set=
ac_cv_env_build_alias_value=
ac_cv_env_host_alias_set=
ac_cv_env_host_alias_value=
ac_cv_env_target_alias_set=
ac_cv_env_target_alias_value=
ac_cv_host=x86_64-unknown-linux-gnu
ac_cv_prog_ac_ct_CC=gcc
ac_cv_target=x86_64-unknown-linux-gnu

## ----------------- ##

AR=''
BAT_EXTENSION=''
BAT_EXTENSION_BAT=''
BAT_EXTENSION_MF=''
BAT_EXTENSION_SH=''
BUILD_DYN=''
BUILD_DYN_BAT=''
BUILD_DYN_ECHO=''
BUILD_DYN_ECHO_BAT=''
BUILD_DYN_MF=''
BUILD_DYN_SH=''
BUILD_EXE=''
BUILD_EXE_BAT=''
BUILD_EXE_ECHO=''
BUILD_EXE_ECHO_BAT=''
BUILD_EXE_MF=''
BUILD_EXE_SH=''
BUILD_LIB=''
BUILD_LIB_BAT=''
BUILD_LIB_ECHO=''
BUILD_LIB_ECHO_BAT=''
BUILD_LIB_MF=''
BUILD_LIB_SH=''
BUILD_OBJ=''
BUILD_OBJ_BAT=''
BUILD_OBJ_ECHO=''
BUILD_OBJ_ECHO_BAT=''
BUILD_OBJ_MF=''
BUILD_OBJ_SH=''
CC='gcc'
CFLAGS=''
COMPILATION_OPTIONS=''
CONF_BOOL=''
CONF_MAX_CHR=''
CONF_SINGLE_MULTIPLE_THREADED_VMS=''
CONF_SINGLE_MULTIPLE_VMS=''
CONF_THREAD_LOCAL_STORAGE_CLASS=''
CONF_THREAD_SYSTEM=''
CONF_VOIDSTAR_WIDTH=''
CPP=''
CPPFLAGS=''
CXX=''
CXXCPP=''
CXXFLAGS=''
C_COMPILER=''
C_COMPILER_BAT=''
C_COMPILER_MF=''
C_COMPILER_SH=''
C_COMP_CLANG=''
C_COMP_GNUC=''
C_COMP_LLVM=''
C_COMP_VISUALC=''
C_PREPROC=''
C_PREPROC_BAT=''
C_PREPROC_MF=''
C_PREPROC_SH=''
DASH_G=''
DASH_KPIC=''
DASH_O1=''
DASH_O2=''
DASH_OPT_IEEE_NaN_inf_ON=''
DASH_OPT_IEEE_comparisons_ON=''
DASH_OPT_Olimit_0=''
DASH_TENV_large_GOT=''
DASH_W=''
DASH_Wall=''
DASH_Wno_unused=''
DASH_Wno_write_strings=''
DASH_b=''
DASH_bundle=''
DASH_call_shared=''
DASH_dynamiclib=''
DASH_expect_unresolved=''
DASH_fPIC=''
DASH_fbranch_probabilities=''
DASH_flat_namespace_undefined_suppress=''
DASH_fmodulo_sched=''
DASH_fno_common=''
DASH_fno_keep_inline_dllexport=''
DASH_fno_math_errno=''
DASH_fno_move_loop_invariants=''
DASH_fno_strict_aliasing=''
DASH_fno_trapping_math=''
DASH_fomit_frame_pointer=''
DASH_fpic=''
DASH_fprofile_arcs=''
DASH_freschedule_modulo_scheduled_loops=''
DASH_fschedule_insns2=''
DASH_ftest_coverage=''
DASH_fullwarn=''
DASH_fwrapv=''
DASH_g=''
DASH_ieee=''
DASH_mieee=''
DASH_mieee_fp=''
DASH_mieee_with_inexact=''
DASH_no_cpp_precomp=''
DASH_p=''
DASH_pg=''
DASH_rdynamic=''
DASH_shared=''
DASH_woff_1110_1174_1209_1552_3201=''
DASH_xO2=''
DEFS=''
DEFS_BAT=''
DEFS_DYN='-D___DYNAMIC'
DEFS_DYN_BAT=''
DEFS_DYN_MF=''
DEFS_DYN_SH=''
DEFS_EXE=''
DEFS_EXE_BAT=''
DEFS_EXE_MF=''
DEFS_EXE_SH=''
DEFS_LIB=''
DEFS_LIB_BAT=''
DEFS_LIB_MF=''
DEFS_LIB_SH=''
DEFS_MF=''
DEFS_OBJ=''
DEFS_OBJ_BAT=''
DEFS_OBJ_MF=''
DEFS_OBJ_SH=''
DEFS_SH=''
ECHO_C=''
ECHO_N='-n'
ECHO_T=''
EGREP=''
ENABLE_ABSOLUTE_SHARED_LIBS=''
ENABLE_COMPILER_NAME=''
ENABLE_GUIDE=''
ENABLE_INTERPRETER_NAME=''
ENABLE_MULTIPLE_VERSIONS=''
ENABLE_SHARED=''
ENABLE_SYMLINKS=''
ENABLE_VERSIONED_SHARED_LIBS=''
EXEEXT=''
EXE_EXTENSION=''
EXE_EXTENSION_BAT=''
EXE_EXTENSION_MF=''
EXE_EXTENSION_SH=''
FIXLIB=''
FLAGS_DYN=''
FLAGS_DYN_BAT=''
FLAGS_DYN_MF=''
FLAGS_DYN_SH=''
FLAGS_EXE=''
FLAGS_EXE_BAT=''
FLAGS_EXE_MF=''
FLAGS_EXE_SH=''
FLAGS_LIB=''
FLAGS_LIB_BAT=''
FLAGS_LIB_MF=''
FLAGS_LIB_SH=''
FLAGS_OBJ=''
FLAGS_OBJ_BAT=''
FLAGS_OBJ_MF=''
FLAGS_OBJ_SH=''
GAMBCGSCLIB=''
GAMBCGSCLIB_BAT=''
GAMBCGSCLIB_MF=''
GAMBCGSCLIB_SH=''
GAMBCGSILIB=''
GAMBCGSILIB_BAT=''
GAMBCGSILIB_MF=''
GAMBCGSILIB_SH=''
GAMBCLIB=''
GAMBCLIB_BAT=''
GAMBCLIB_DEFS=''
GAMBCLIB_DEFS_BAT=''
GAMBCLIB_DEFS_MF=''
GAMBCLIB_DEFS_SH=''
GAMBCLIB_MF=''
GAMBCLIB_SH=''
GCC_42_OR_43=''
GIT=''
GREP=''
HAVE_SPECIAL_CC=''
HAVE_SPECIAL_CXX=''
HELP_BROWSER=''
HG=''
INSTALL=''
INSTALL_DATA=''
INSTALL_LIB=''
INSTALL_PROGRAM=''
LDFLAGS=''
LIBOBJS=''
LIBS=''
LIBS_BAT=''
LIBS_MF=''
LIBS_SH=''
LIB_EXTENSION=''
LIB_EXTENSION_BAT=''
LIB_EXTENSION_MF=''
LIB_EXTENSION_SH=''
LIB_MAJOR_VERSION_SUFFIX=''
LIB_PREFIX=''
LIB_PREFIX_BAT=''
LIB_PREFIX_MF=''
LIB_PREFIX_SH=''
LIB_VERSION_SUFFIX=''
LINK=''
LINK_FOR_INSTALL=''
LINK_FOR_INSTALL_GSC_LIBS=''
LINK_FOR_INSTALL_GSI_LIBS=''
LN_S=''
LTLIBOBJS=''
MAKE_LIBRARY=''
MAKE_LIBRARY_FOR_INSTALL=''
MAKE_LIBRARY_FOR_INSTALL_LIBS=''
OBJEXT=''
OBJ_EXTENSION=''
OBJ_EXTENSION_BAT=''
OBJ_EXTENSION_MF=''
OBJ_EXTENSION_SH=''
OS_WIN32=''
PACKAGE_BUGREPORT='gambit@iro.umontreal.ca'
PACKAGE_NAME='Gambit-C'
PACKAGE_SHORTNAME='gambc'
PACKAGE_STRING='Gambit-C v4.7.4'
PACKAGE_TARNAME='gambc-v4_7_4'
PACKAGE_URL=''
PACKAGE_VERSION='v4.7.4'
PATH_SEPARATOR=':'
POSSIBLE_LLVM_GCC_LABEL_VALUES_BUG=''
QTINCPATH=''
RANLIB=''
RC=''
RTLIBSUBSYS=''
SETDLPATH=''
SETDLPATHBOOT=''
SET_MAKE=''
SHELL='/bin/sh'
XMKMF=''
X_CFLAGS=''
X_EXTRA_LIBS=''
X_FLAGS=''
X_LIBS=''
X_PRE_LIBS=''
ac_ct_CC='gcc'
ac_ct_CXX=''
bat=''
bindir='${exec_prefix}/bin'
build='x86_64-unknown-linux-gnu'
build_alias=''
build_cpu='x86_64'
build_os='linux-gnu'
build_vendor='unknown'
datadir='${datarootdir}'
datarootdir='${prefix}/share'
docdir='${datarootdir}/doc/${PACKAGE_TARNAME}'
dvidir='${docdir}'
emacsdir=''
exe=''
exec_prefix='NONE'
host='x86_64-unknown-linux-gnu'
host_alias=''
host_cpu='x86_64'
host_os='linux-gnu'
host_vendor='unknown'
htmldir='${docdir}'
includedir='${prefix}/include'
infodir='${datarootdir}/info'
libdir='${exec_prefix}/lib'
libexecdir='${exec_prefix}/libexec'
localedir='${datarootdir}/locale'
localstatedir='${prefix}/var'
mandir='${datarootdir}/man'
obj=''
oldincludedir='/usr/include'
pdfdir='${docdir}'
prefix='NONE'
program_transform_name='s,x,x,'
psdir='${docdir}'
sbindir='${exec_prefix}/sbin'
sharedstatedir='${prefix}/com'
srcdirpfx=''
sysconfdir='${prefix}/etc'
target='x86_64-unknown-linux-gnu'
target_alias=''
target_cpu='x86_64'
target_os='linux-gnu'
target_vendor='unknown'

## ----------- ##

/* confdefs.h */
#define PACKAGE_NAME "Gambit-C"
#define PACKAGE_TARNAME "gambc-v4_7_4"
#define PACKAGE_VERSION "v4.7.4"
#define PACKAGE_STRING "Gambit-C v4.7.4"
#define PACKAGE_BUGREPORT "gambit@iro.umontreal.ca"
#define PACKAGE_URL ""

configure: exit 77
$ exit

Script done on Mon 02 Mar 2015 10:30:20 AM PST

**Comment by feeley** [comment]
It sounds like you don't have a functional C compiler installed on your machine.  Can you try compiling a "hello world" program to see if that works?  I.e.:

% cat hw.c
#include <stdio.h>
int main() { printf("hello\n"); return 0; }
% gcc -o hw.exe hw.c

**Comment by pasha23** [comment]
*pasha@ThinkCentre-M90p** ~ $* cat hw.c

#include

int main() { printf("hello\n"); return 0; }

*pasha@ThinkCentre-M90p** ~ $* gcc -o hw.exe hw.c

hw.c:1:9: error: #include expects "FILENAME" or <FILENAME>

 #include

         ^

hw.c: In function ‘main’:

hw.c:2:14: warning: incompatible implicit declaration of built-in function
‘printf’ [enabled by default]

 int main() { printf("hello\n"); return 0; }

              ^

*pasha@ThinkCentre-M90p** ~ $*

**Comment by pasha23** [comment]
*pasha@ThinkCentre-M90p** ~ $* cat hw.c

int main() { printf("hello\n"); return 0; }

*pasha@ThinkCentre-M90p** ~ $* gcc -o hw.exe hw.c

hw.c: In function ‘main’:

hw.c:1:14: warning: incompatible implicit declaration of built-in function
‘printf’ [enabled by default]

 int main() { printf("hello\n"); return 0; }

              ^

*pasha@ThinkCentre-M90p** ~ $* ./hw.exe

hello

*pasha@ThinkCentre-M90p** ~ $*

**Comment by feeley** [comment]
Sorry, there was a part missing... it is

`#include <stdio.h>`

**Comment by pasha23** [comment]
OK, now there are no errors or warnings.  The executable works.

pasha@ThinkCentre-M90p ~ $ cat hw.c
#include <stdio.h>
int main() { printf("hello\n"); return 0; }
pasha@ThinkCentre-M90p ~ $ gcc -o hw.exe hw.c
pasha@ThinkCentre-M90p ~ $ ./hw.exe
hello
pasha@ThinkCentre-M90p ~ $

In fact, configure is working now.  I don't know what changed.  But we can
close this issue.

Sorry for wasting your time.  And thanks for building Gambit Scheme!
