### ISSUE TITLE
Uncallable functions not removed by compiler

### ISSUE THREAD

**Issue by gambiteer** [feeley/gambit#113]
Marc:

I'm looking at the expansion of _num.scm by gsc.

It keeps the function ##fast-gcd, even though it isn't (and can't be) called; it has two copies of determined-minimal? even though, again, it isn't called.

I thought gsc got rid of dead code.

Brad

**Comment by feeley** [comment]
How do you know it wasn't removed from the final code?

**Comment by gambiteer** [comment]
On 04/20/2015 06:26 PM, Marc Feeley wrote:
> How do you know it wasn't removed from the final code?

OK, how can I tell?  Can I dump the AST at several points in the process?

I just looked at the generated C code, and I agree, it looks like they
were removed from the final code.  But I can't tell for sure.

Brad

**Comment by feeley** [comment]
But wait... ##fast-gcd is called by exact-gcd and exact-gcd is called by the main expression in ##gcd.  So why do you think it is dead code?

**Comment by gambiteer** [comment]
On 04/21/2015 09:36 AM, Marc Feeley wrote:
> But wait... ##fast-gcd is called by exact-gcd and exact-gcd is called by
> the main expression in ##gcd. So why do you think it is dead code?

If you look at the output of 'gsc -expansion ... _num.scm' you'll see
that ##fast-gcd is inlined into its caller, so when I saw a separate,
named copy of ##fast-gcd in the letrec list, I thought it was also left
in the C code.

I believe now it wasn't, so you can close this if you like.

Brad
