### ISSUE TITLE
Incorrect handling of non-ASCII characters in paths

### ISSUE THREAD

**Issue by jgesswein** [feeley/gambit#115]
Routines working with file system paths (`create-directory`, `rename-file`, `copy-file` etc.) do not handle non-ASCII characters properly. When reading file names on OS X with `directory-files` for instance the name "äöü" is returned as "a\314\210o\314\210u\314\210" where "\314\210" is the UTF-8 encoding of U+0308 (combining diaeresis). The name should be returned as "a\u0308o\u0308u\u0308" or as "äöü" (if characters are combined). On OS X and Linux the file system stores names in UTF-8 and the routines working with files should use encoding "uft8" instead of "native".

**Comment by feeley** [comment]
Do you have time to look into a fix and send a pull request?

**Comment by ltp-lab** [comment]
I have worked on a fix and will commit it soon.

**Comment by feeley** [comment]
I've just committed a fix.  The path encoding is now selectable with a configure option, and the default is utf8 except on Windows.

**Comment by alvatar** [comment]
What is the default on Windows then? UTF-16?

**Comment by gambiteer** [comment]
On 05/04/2015 12:28 PM, Álvaro Castro-Castilla wrote:
> What is the default on Windows then? UTF-16?
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/feeley/gambit/issues/115#issuecomment-98772570>.
> 
The patch says it's UCS2, but I don't know what that means.

Brad

**Comment by alvatar** [comment]
Quoting wikipedia: _UTF-16 developed from an earlier fixed-width 16-bit encoding known as UCS-2 (for 2-byte Universal Character Set) once it became clear that a fixed-width 2-byte encoding could not encode enough characters to be truly universal._
