### ISSUE TITLE
Trying to start a REPL when no controlling terminal is available

### ISSUE THREAD

**Issue by gcartier** [feeley/gambit#147]
On Mac OS X, when launching a Gambit application built as a bundle, if an error occurs, Gambit correctly detects that there is no controlling terminal and thus sends all output to the NSLog, but then tries to start a REPL which causes the process to hang.

It is of course possible to use -:dq to force Gambit to quit on exceptions, but as Gambit has already detected that there was no controlling terminal, I suggest that even on -:dr it exits as if -:dq. Having to manually add -:dq is difficult in a cross-platform context where for example I would rather use -:dr as Windows can always open a controlling terminal.

**Comment by feeley** [comment]
Fixed by commit 9eae82a833cd4e5537c48e4c06212e7fe95ee8cf

**Comment by feeley** [comment]
Fixed in a better way by commit a5b6ee34c5ab04bd44672de3198ac12b8a897651
