### ISSUE TITLE
no fxbitwise-and, ##fixnum.bitwise-and, grrrrh

### ISSUE THREAD

**Issue by gambiteer** [feeley/gambit#165]
*** ERROR IN #<procedure #2>, "generic-arrays.scm"@904.12 -- Unbound variable: fxbitwise-and
1> ##fixnum.bitwise-and
*** ERROR IN (console)@2.1 -- Unbound variable: ##fixnum.bitwise-and

I guess those definitions weren't so redundant after all.

heine:~/programs/gambit/gambit> gsi -v
v4.8.1 20151017174904 x86_64-unknown-linux-gnu "./configure 'CC=/usr/local/gcc-5.1.0/bin/gcc -march=native' '--enable-single-host' '--enable-shared' '--enable-multiple-versions'"

**Comment by feeley** [comment]
It is fxand, fxior, fxxor, fxnot, ...

**Comment by gambiteer** [comment]
OK, sorry.
