### ISSUE TITLE
'make check' fails with --enable-multiple-vms

### ISSUE THREAD

**Issue by aking** [feeley/gambit#170]
From a fresh gambit github checkout and using './configure --enable-multiple-vms' & 'make -j4 from-scratch', 'make-check' fails on the 9th test:

````
------------ TEST 9 (dynamic compilation and loading of a module)
rm -rf mem.o mem.o*
../gsc/gsc -:~~bin=../bin,~~lib=../lib,~~include=../include -f -warnings mem.scm
ld: illegal thread local variable reference to regular symbol ____tls_ptr for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
*** ERROR IN ##main -- C compilation or link failed while compiling "mem.scm"
make[1]: *** [test9] Error 70
make: *** [check] Error 2
gem:gambit aking$
````

System Info:

gem:gambit aking$ uname -a
Darwin gem.local 15.2.0 Darwin Kernel Version 15.2.0: Fri Nov 13 19:56:56 PST 2015; root:xnu-3248.20.55~2/RELEASE_X86_64 x86_64

gem:gambit aking$ clang --version
Apple LLVM version 7.0.2 (clang-700.1.81)
Target: x86_64-apple-darwin15.2.0
Thread model: posix

gem:gambit aking$ xcodebuild -version
Xcode 7.2
Build version 7C68

**Comment by feeley** [comment]
Repeat of #109
