### ISSUE TITLE
Crash in javascript runtime in ##bignum.*; problem in compiler?

### ISSUE THREAD

**Issue by gambiteer** [feeley/gambit#171]
With the following program:

[chud2.txt](https://github.com/feeley/gambit/files/95341/chud2.txt)

With the following compiler:

firefly:~/programs/gambit/gambit> gsc -v
v4.8.3 20160116034745 x86_64-unknown-linux-gnu "./configure 'CC=gcc -march=native' '--enable-single-host' '--enable-multiple-versions' '--enable-shared'"

with the following build commands:

firefly:~/programs/gambit/gambit> cd lib
firefly:~/programs/gambit/gambit/lib> make _gambit.js
LD_LIBRARY_PATH=..:/usr/local/Gambit/current/lib:/usr/local/netpbm10/lib: ../gsc/gsc -:~~bin=../bin,~~lib=../lib,~~include=../include -f -target js -prelude "(##include \"header.scm\")" -o _gambit.js ../lib/_univlib.scm
firefly:~/programs/gambit/gambit/lib> cd ..
firefly:~/programs/gambit/gambit> gsc -:=. -warnings -never-return-jump -target js -link chud2.scm 
firefly:~/programs/gambit/gambit> cat chud2_.js chud2.js lib/_gambit.js > ! crap.js 

Gives the following error:
firefly:~/programs/gambit/gambit> node crap.js
Chudnovsky's algorithm using binary splitting in Gambit Scheme: digits 10, CPU time: .011999999999999997.
Last 5 digits 26535.
Chudnovsky's algorithm using binary splitting in Gambit Scheme: digits 100, CPU time: .0040000000000000036.
Last 5 digits 70679.
/home/lucier/programs/gambit/gambit/crap.js:69444
function g_bb18__23__23_bignum_2e__2a_() {
                                      ^

RangeError: Maximum call stack size exceeded
    at g_bb18__23__23_bignum_2e__2a_ (/home/lucier/programs/gambit/gambit/crap.js:69444:39)
    at g_bb18__23__23_bignum_2e__2a_ (/home/lucier/programs/gambit/gambit/crap.js:69451:12)
    at g_bb18__23__23_bignum_2e__2a_ (/home/lucier/programs/gambit/gambit/crap.js:69451:12)
    at g_bb18__23__23_bignum_2e__2a_ (/home/lucier/programs/gambit/gambit/crap.js:69451:12)
    at g_bb18__23__23_bignum_2e__2a_ (/home/lucier/programs/gambit/gambit/crap.js:69451:12)
    at g_bb18__23__23_bignum_2e__2a_ (/home/lucier/programs/gambit/gambit/crap.js:69451:12)
    at g_bb18__23__23_bignum_2e__2a_ (/home/lucier/programs/gambit/gambit/crap.js:69451:12)
    at g_bb18__23__23_bignum_2e__2a_ (/home/lucier/programs/gambit/gambit/crap.js:69451:12)
    at g_bb18__23__23_bignum_2e__2a_ (/home/lucier/programs/gambit/gambit/crap.js:69451:12)
    at g_bb18__23__23_bignum_2e__2a_ (/home/lucier/programs/gambit/gambit/crap.js:69451:12)

The Javascript routine is

function g_bb18__23__23_bignum_2e__2a_() {              <== line 69444
  g_inttemp1 = g_stack[g_sp-2].digits[g_r2] + g_stack[g_sp-6].digits[g_r1] * g_stack[g_sp] + g_r3;
  g_stack[g_sp-2].digits[g_r2] = g_inttemp1 & 16383;
  g_r3 = g_inttemp1 >> 14;
  g_r2 = g_r2 + 1;
  g_r1 = g_r1 + 1;
  if (g_r1 < g_stack[g_sp-5]) {
    return g_bb18__23__23_bignum_2e__2a_();      <===== line 69451
  } else {
    return g_bb19__23__23_bignum_2e__2a_();
  }
}

The problem disappears if I build gambit.js with -never-return-jump

**Comment by gambiteer** [comment]
You know, that looks like the code for this loop in naive-mul:

                (let loop2 ((i 0)
                            (j k)
                            (carry 0))
                  (if (##fx< i x-length)
                    (loop2 (##fx+ i 1)
                           (##fx+ j 1)
                           (##bignum.mdigit-mul! result
                                                 j
                                                 x
                                                 i
                                                 multiplier
                                                 carry))
                    (begin
                      (##bignum.mdigit-set! result j carry)
                      (loop1 (##fx+ k 1)))))))

And you're right, I do declare not interrupts-enabled, and it could just be that the runtime's blowing the stack because the compiler doesn't do real TCO.

**Comment by feeley** [comment]
I've added a check for loops with (not interrupts-enabled) that unwinds the host stack.  So now you shouldn't have to use the -never-return-jump option.  Could you check this works?

**Comment by gambiteer** [comment]
On 01/20/2016 12:44 AM, Marc Feeley wrote:
> I've added a check for loops with (not interrupts-enabled) that unwinds
> the host stack. So now you shouldn't have to use the -never-return-jump
> option. Could you check this works?

Yes, it fixes the problem while using the naive bignum algorithms.

I haven't checked whether it makes the fast bignum algorithms slower, 
but that's not so important.

Brad
