### ISSUE TITLE
Some prio* - Additional debug feature request!: Make option for C backend to track file:line of last lines of Scheme code run in global variables

### ISSUE THREAD

**Issue by adam-7** [feeley/gambit#172]
SIGSEGV tracking can be extremely challenging, and can happen easily from heap corruption, in particular in relation with FFI code.

It's made worse by the fact that when a crash happens, GDB's "bt" easily becomes useless, partially because of Gambit's stack model.

GDB's "info variables" tends to still remain intact after SIGSEGV though, meaning that any debug info stored in global variables by the GVM are usable -

Therefore, I very kindly ask you to implement an optional debug feature for Gambit that sugars all output C code with the file and line executed, and then builds a history of that.

I guess the module name is already stored as a char* somewhere. The line in the code is just an integer.

The tracking could even be made long by just keeping an array of char* and int, and then having a pointer telling where it's writing now e.g. a global "int history_storage_pointer = 0" and at each store you do "history_storage_pointer = history_storage_pointer++ % 100".

Of course this would impose an overhead on code execution of something like 10-50%, however I would be more than fine with that. All alternative options have higher overhead.

Please let me know what you think - thanks!!

**Comment by feeley** [comment]
This has been added.
