### ISSUE TITLE
Segmentation fault in ##object->global-var

### ISSUE THREAD

**Issue by gambiteer** [feeley/gambit#175]
With the latest git sources configured with

heine:~/programs/gambit/gambit/lib> gsc -v
v4.8.4 20160129173624 x86_64-unknown-linux-gnu "./configure 'CC=gcc -march=native' '--enable-single-host' '--enable-multiple-versions' '--enable-debug' '--enable-track-scheme'"

I'm getting a segfault:

*** ERROR IN 
Program received signal SIGSEGV, Segmentation fault.
0x0000000000542b18 in ___H__20___kernel (___ps=0x11e1600 <___gstate0>) at _kernel.scm:3679
3679	   if (___ARG2 == ___FAL)

I can do

(gdb) info locals
___RESULT = 0
p = 0x7ffff7ecf02100
___pc = 14845025
___temp = 14845025
___hp = 0x4915f030
___fp = 0xf8f801 <___G_c_23_univ_2d_rtlib_2d_gen+17>
___r0 = 14845089
___r1 = 140737334976193
___F64V1 = 0
___hlbltbl = {0x0, 0x52f2f0 <___H__20___kernel+209>, 0x52f401 <___H__20___kernel+482>, 
<whole lot of stuff omitted>

The C expansion of the code starts with:

#undef ___PH_PROC
#define ___PH_PROC ___H__23__23_object_2d__3e_global_2d_var
#undef ___PH_LBL0
#define ___PH_LBL0 619
#undef ___PD_ALL
#define ___PD_ALL ___D_HEAP ___D_FP ___D_R0 ___D_R1 ___D_R2 ___D_R3 ___D_R4
#undef ___PR_ALL
#define ___PR_ALL ___R_HEAP ___R_FP ___R_R0 ___R_R1 ___R_R2 ___R_R3 ___R_R4
#undef ___PW_ALL
#define ___PW_ALL ___W_HEAP ___W_FP ___W_R0 ___W_R1 ___W_R2 ___W_R3 ___W_R4
___BEGIN_P_COD
___BEGIN_P_HLBL
___DEF_P_HLBL_INTRO
___DEF_P_HLBL(___L0__23__23_object_2d__3e_global_2d_var)
___END_P_HLBL
___BEGIN_P_SW
___DEF_SLBL(0,___L0__23__23_object_2d__3e_global_2d_var)
   ___IF_NARGS_EQ(2,___NOTHING)
   ___WRONG_NARGS(0,2,0,0)
___DEF_GLBL(___L__23__23_object_2d__3e_global_2d_var)
#line 3676 "_kernel.scm"
#define ___ARG1 ___R1
#line 3676
#define ___ARG2 ___R2
#line 3676
{ ___SCMOBJ ___RESULT;
#line 3676

   ___glo_struct *p = ___GSTATE->mem.glo_list_head;
   if (___ARG2 == ___FAL)                                         <============ Fails here
     while (p != 0 && ___GLOCELL(p->val) != ___ARG1)
       p = p->next;
   else
     while (p != 0 && ___PRMCELL(p->prm) != ___ARG1)
       p = p->next;

I can't see a ___r2 variable, which doesn't make sense.

This is stopping my work work.  Blah.

**Comment by gambiteer** [comment]
The assembly code around this is

.L1644:
.LBB171:
	.loc 2 3677 0
	movq	___gstate0@GOTPCREL(%rip), %rax
	movq	928(%rax), %rax
	movq	%rax, -20568(%rbp)
	.loc 2 3678 0
	cmpq	$-2, -21528(%rbp)
	jne	.L1654
	.loc 2 3679 0
	jmp	.L1651
.L1653:
	.loc 2 3680 0
	movq	-20568(%rbp), %rax
	movq	16(%rax), %rax
	movq	%rax, -20568(%rbp)
.L1651:
	.loc 2 3679 0
	cmpq	$0, -20568(%rbp)
	je	.L1652
	.loc 2 3679 0 is_stmt 0 discriminator 1
	movq	-20568(%rbp), %rax
	movq	(%rax), %rax
	cmpq	%r13, %rax
	jne	.L1653
	jmp	.L1652

**Comment by feeley** [comment]
What's the program you are compiling?

**Comment by gambiteer** [comment]
After further review I think this is fault of my code (I think I blew the C stack with non-tail calls after disabling interrupts in a silly sort routine) and it just happened to show up in _kernel.scm code.

So I'm going to close this for now.
