### ISSUE TITLE
copy-file changes modification time

### ISSUE THREAD

**Issue by gcartier** [feeley/gambit#182]
When copying a file using copy-file, the destination file is given the current time as modification time instead of preserving the modification time of the source file.

Note that I only tested this on Mac OS X.

**Comment by feeley** [comment]
copy-file does not guarantee preserving the modification time of the source file.  This will depend on the operating system and conditions.  For example, even Window's CopyFile which aims to preserve the modification time, it may not be set in some cases.  So for portability and reliability, it is best to set the modification time explicitly with a call to file-last-access-and-modification-times-set! .
