### ISSUE TITLE
___FIXASHL is incorrect for negative arguments

### ISSUE THREAD

**Issue by gambiteer** [feeley/gambit#184]
Discovered when building and testing Gambit with

./configure CC='gcc -fsanitize=address -fsanitize=undefined -fsanitize-recover=all -g' --enable-shared
make mostlyclean
make -j 8
make -i check

gives

 _num.c:43916:4: runtime error: left shift of negative value -4

This is
  ___SET_R1(___FIXASHL(___FIX(-1L),___R1))
I looked at ___FIXASHL in gambit.h.in and couldn't figure out how to fix it.

**Comment by feeley** [comment]
Same as issue #185.  Fixed.
