### ISSUE TITLE
display and pretty-print treat uninterned symbols differently.

### ISSUE THREAD

**Issue by gambiteer** [feeley/gambit#196]
This is screwing me up trying to generate some scheme code.

(display (list (gensym)))
(g2)> (pretty-print (list (gensym)))
(#:g3)
> (pp (list (gensym)))
(#:g4)

Shouldn't pretty-print treat uninterned symbols the same way display does?

Bug or feature?  (I'm almost inclined to change it myself, but I thought I'd ask first.)

**Comment by feeley** [comment]
Well ```(display <string>)``` will display the string without the double quotes and escaped characters, and ```(display <symbol>)``` similarly does not display the vertical bars and any escaped characters, for example ```(display '|a b|)``` in other words for symbols display will do ```(display (symbol->string <symbol>))```.  So the behavior is consistent.  Why don't you use ```(write <symbol>)``` in this case?  If they behaved the same there would be no need for both.

**Comment by gambiteer** [comment]
On 04/15/2016 06:09 PM, Marc Feeley wrote:
> Well |(display <string>)| will display the string without the double
> quotes and escaped characters, and |(display <symbol>)| similarly does
> not display the vertical bars and any escaped characters, for example
> |(display '|a b|)| in other words for symbols display will do |(display
> (symbol->string <symbol>))|. So the behavior is consistent. Why don't
> you use |(write <symbol>)| in this case? If they behaved the same there
> would be no need for both.


I'm saying that *pretty-print* should print *uninterned symbols* the way 
display does, not the way write does.

I'm building a form, and sometimes I want to simply "display" it and 
sometimes for debugging reasons I want to "pretty-print" it.  I use 
(gensym) to generate uninterned symbols as variable names, and this 
difference is screwing me up.

Brad

**Comment by feeley** [comment]
pretty-print is meant to work like write but adds line breaks and indentation to make it humanly readable.  It would be wrong for it to map uninterned symbols to interned symbol syntax.  If you don't like this, redefine gensym or redefine ##wr.

**Comment by gambiteer** [comment]
Display is meant to work like write but makes it more readable.  To have two procedures (display and pretty-print) that try to make the output of write more readable in two incompatible ways is counterproductive. 

Brad

**Comment by feeley** [comment]
I disagree that display is meant to write an object in a more readable way.  The fact that ```(display "hello")``` doesn't display doublequotes is not a matter of readability.

In any case "more readable" is a subjective notion.  It would be more readable for you because of your specific use case (wanting to abstract away the fact that a symbol is interned or not).  But for the use case I encounter it is more readable to distinguish interned and uninterned symbols.  Also, it is important for pretty-print just like write to have "write/read" invariance, among other things because pretty-print is used by the REPL to write the result of an evaluation.

The behaviour you are looking for can be obtained by adding this to your gambext.scm file:

```
(include "~~lib/_gambit#.scm")

(define (copy-writeenv we style)
  (##make-writeenv
   style ;;(macro-writeenv-style we)
   (macro-writeenv-port we)
   (macro-writeenv-readtable we)
   (macro-writeenv-marktable we)
   (macro-writeenv-force? we)
   (macro-writeenv-width we)
   (macro-writeenv-shift we)
   (macro-writeenv-close-parens we)
   (macro-writeenv-level we)
   (macro-writeenv-limit we)
   (macro-writeenv-max-unescaped-char we)))

(set! ##wr
      (let ((old-wr ##wr))
        (lambda (we obj)
          (if (##symbol? obj)
              (let ((style (macro-writeenv-style we)))
                (##wr-symbol
                 (copy-writeenv we (if (eq? style 'pretty-print) 'display style))
                 obj))
              (old-wr we obj)))))
```
