### ISSUE TITLE
Batchjob for building with Visual C++ broken

### ISSUE THREAD

**Issue by jgesswein** [feeley/gambit#198]
The batch job for building Gambit with Visual C++ Express does not work. There are missing files and the creation of header “gambit.h” is not correct. Attached is a batch job “[vc2012_bat.txt](https://github.com/feeley/gambit/files/222189/vc2012_bat.txt)” (renamed so that it can be attached…) that works on my system for compiling Gambit v4.7.3.

**Comment by feeley** [comment]
I have added your batch file and corrected the other batch files for MSVC++.  Thanks!
