### ISSUE TITLE
Build error under Arch Linux 64 bit

### ISSUE THREAD

**Issue by stefanhusmann** [feeley/gambit#199]
Hello,

this happens when I compile gambit-c using https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=gambit-c-git

gcc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4   -Wno-unused -Wno-write-strings -O2 -fno-math-errno -fschedule-insns2 -fno-strict-aliasing -fno-trapping-math -fwrapv -fmodulo-sched -freschedule-modulo-scheduled-loops -fomit-frame-pointer -fPIC -fno-common -mieee-fp   -I"../include" -c -o "_kernel.o" -I. -DHAVE_CONFIG_H -D___GAMBITDIR="\"/usr\"" -D___GAMBITDIR_LIB="\"/usr/lib/gambit-c\"" -D___GAMBITDIR_DOC="\"/usr/share/gambit-c\"" -D___GAMBITDIR_INFO="\"/usr/share/info\"" -D___SYS_TYPE_CPU="\"x86_64\"" -D___SYS_TYPE_VENDOR="\"unknown\"" -D___SYS_TYPE_OS="\"linux-gnu\"" -D___CONFIGURE_COMMAND="\"./configure '--prefix=/usr' '--docdir=/usr/share/gambit-c' '--infodir=/usr/share/info' '--libdir=/usr/lib/gambit-c' '--enable-c-opt' '--enable-gcc-opts' '--enable-single-host' '--disable-shared' '--enable-compiler-name=gambitc' '--enable-interpreter-name=gambiti' 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4' 'LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro' 'CPPFLAGS=-D_FORTIFY_SOURCE=2' 'CXXFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4'"\" -D___OBJ_EXTENSION="\".o\"" -D___EXE_EXTENSION="\"\"" -D___BAT_EXTENSION="\"\"" -D___PRIMAL _kernel.c -D___LIBRARY
_kernel.c: In function '___H__20___kernel':
_kernel.c:14100:37: error: '___gstate_mem {aka struct ___gstate_mem_struct}' has no member named 'glo_list_head'
    ___glo_struct *p = ___GSTATE->mem.glo_list_head;
                                     ^
makefile:164: recipe for target '_kernel.o' failed
make[2]: *** [_kernel.o] Error 1

It used to work, but obviously something on my machine changed, maybe a missing dependency?

**Comment by gambiteer** [comment]
The github sources are in an inconsistent state, if you want to build 
gambit right now use a release tar file from the home page.

Brad

**Comment by feeley** [comment]
Could you try the new build instructions.  That is:

```
git clone https://github.com/feeley/gambit.git
cd gambit
./configure
make -j4 latest-release
./configure --enable-single-host
make -j4 from-scratch
make check
sudo make install
```

**Comment by gambiteer** [comment]
Seems to work.

Brad

**Comment by stefanhusmann** [comment]
Builds fine for me, too. Thanks!

**Comment by feeley** [comment]
Great!
