### ISSUE TITLE
Bug using external keyboard on iOS

### ISSUE THREAD

**Issue by david94133** [feeley/gambit#89]
When using an external keyboard on iOS, the tab bar at the bottom is inaccessible.

When not using an external keyboard, the tab bar is exposed by hiding the software-keyboard, which also hides the keyboard extension. But, when using an external keyboard, there is no "hide keyboard" key, and therefore the keyboard extension cannot be hidden. It covers the tab bar.

An easy solution to this is to provide an option to just not use the keyboard extension, which isn't very useful when using a full-sized external keyboard anyway.

Right now, the only way I can switch between the "repl" and "edit" tabs, for example, is to turn off my external keyboard first.

**Comment by feeley** [comment]
The keyboard handling code has been reimplemented and this issue is no longer relevant.
