### ISSUE TITLE
Gambit repo doesn't have tags and releases beyond v4.7.0

### ISSUE THREAD

**Issue by michel-slm** [feeley/gambit#93]
The tags and releases are only available up to Gambit-C 4.7.0 -- perhaps they were made in a private Git repo and haven't been pushed to Github?

**Comment by feeley** [comment]
OK this is now fixed.  A "make push" now pushes the changes and the tags.

**Comment by stefanhusmann** [comment]
Thanks.

**Comment by michel-slm** [comment]
Thanks @feeley !
