### ISSUE TITLE
configure --enable-coverage should enable -track-scheme option in gsc

### ISSUE THREAD

**Issue by gambiteer** [feeley/gambit#94]
I might have some spare time in the future, and I thought I might add to Gambit's test suite to test the coverage of the library code, especially in _num.scm.

When I configured with --enable-coverage, it worked, but the coverage is of _num.c, not _num.scm.

I'm pretty good at reading the C files and figuring out where each line came from, but it's not worth it for this application.

**Comment by feeley** [comment]
I have added a --enable-track-scheme configuration option.  You have to ./configure --enable-track-scheme --enable-coverage and after a successful "make" you have to "make bootclean; make".
