### ISSUE TITLE
make mostly-clean shoud remove .gcno and .gcda files

### ISSUE THREAD

**Issue by gambiteer** [feeley/gambit#97]
Or maybe make real-clean should do this, I don't know.

I guess if we're going to regenerate the C files, then the coverage files aren't o much use.

Brad

**Comment by feeley** [comment]
Which configuration options generate these files?

**Comment by gambiteer** [comment]
Enable-coverAge

**Comment by feeley** [comment]
On my machine I can't even build with --enable-coverage (gcc runs out of virtual memory).  I looked at the makefiles and I think the .gcno etc files should be removed by a "make clean" as is the case now.  It is "make bootclean" that removes the generated .c files.

**Comment by gambiteer** [comment]
On 01/17/2015 12:46 PM, Marc Feeley wrote:
>
> On my machine I can't even build with --enable-coverage (gcc runs out 
> of virtual memory). I looked at the makefiles and I think the .gcno 
> etc files should be removed by a "make clean" as is the case now. It 
> is "make bootclean" that removes the generated .c files.
>

Versions 4.8.*, 4.9.*, and 5.0 (development, with new numbering scheme) 
are all buggy when compiling gambit with -ftest-coverage 
-fprofiling-arcs; on a machine with 160 GB of RAM it crashed after 
running out of memory compiling _io.c.

I've been using

    zariski-168% gcc -v
    Using built-in specs.
    Target: x86_64-redhat-linux
    Configured with: ../configure --prefix=/usr --mandir=/usr/share/man
    --infodir=/usr/share/info
    --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap
    --enable-shared --enable-threads=posix --enable-checking=release
    --with-system-zlib --enable-__cxa_atexit
    --disable-libunwind-exceptions --enable-gnu-unique-object
    --enable-languages=c,c++,objc,obj-c++,java,fortran,ada
    --enable-java-awt=gtk --disable-dssi
    --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-1.5.0.0/jre
    --enable-libgcj-multifile --enable-java-maintainer-mode
    --with-ecj-jar=/usr/share/java/eclipse-ecj.jar
    --disable-libjava-multilib --with-ppl --with-cloog
    --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
    Thread model: posix
    gcc version 4.4.7 20120313 (Red Hat 4.4.7-11) (GCC)


and

    maclaurin-168% gcc -v
    Using built-in specs.
    Target: x86_64-redhat-linux
    Configured with: ../configure --prefix=/usr --mandir=/usr/share/man
    --infodir=/usr/share/info
    --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap
    --enable-shared --enable-threads=posix --enable-checking=release
    --with-system-zlib --enable-__cxa_atexit
    --disable-libunwind-exceptions --enable-gnu-unique-object
    --enable-languages=c,c++,objc,obj-c++,java,fortran,ada
    --enable-java-awt=gtk --disable-dssi
    --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-1.5.0.0/jre
    --enable-libgcj-multifile --enable-java-maintainer-mode
    --with-ecj-jar=/usr/share/java/eclipse-ecj.jar
    --disable-libjava-multilib --with-ppl --with-cloog
    --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
    Thread model: posix
    gcc version 4.4.7 20120313 (Red Hat 4.4.7-4) (GCC)


on Red Hat Enterprise Linux 6 (and perhaps 5) to build a profiled Gambit.

I've been meaning to submit a gcc bug report, but hoped to get a smaller 
test case.

Brad
