### ISSUE TITLE
Scheduler reported exception on Cygwin64

### ISSUE THREAD

**Issue by colincoates** [feeley/gambit#99]
Hi all,

I have a fresh install of Cygwin64 on Windows 8.1. 

I installed gcc 4.9.2 and then built gambc-4_7_3 using:
> ./configure --enable-single-host
> make
> make install

However, when I run gsi (or gsc) I get a lot of *** ERROR -- Scheduler reported the exception, like:
 
Colin@pepper /cygdrive/c/Users/Colin/Downloads/software/gambit/gambc-v4_7_3
$ /usr/local/Gambit-C/bin/gsi
Gambit v4.7.3

> *** ERROR -- Scheduler reported the exception: #<os-exception #2>
> *** ERROR -- Scheduler reported the exception: #<os-exception #3>
> *** ERROR -- Scheduler reported the exception: #<os-exception #4>
> *** ERROR -- Scheduler reported the exception: #<os-exception #5>
> *** ERROR -- Scheduler reported the exception: #<os-exception #6>
> *** ERROR -- Scheduler reported the exception: #<os-exception #7>
> *** ERROR -- Scheduler reported the exception: #<os-exception #8>
> *** ERROR -- Scheduler reported the exception: #<os-exception #9>
> *** ERROR -- Scheduler reported the exception: #<os-exception #10>
> *** ERROR -- Scheduler reported the exception: #<os-exception #11>

... and so on.

I am guessing this is a bug?

/Colin

**Comment by m-i-k-a-e-l** [comment]
Try v4.7.0 and tell what happened?

**Comment by colincoates** [comment]
I'm seeing the same sort of thing for v4.7.0, M-i-k-a-e-l.

**Comment by feeley** [comment]
When I try on a 32 bit Windows 7 computer there are no errors reported.  I don't have a 64 bit Windows 8.1 installation handy.  Could you try compiling for 32 bits to see if that is the issue?  This can be done with

./configure CC="gcc -m32"

**Comment by colincoates** [comment]
Sorry about my delay in replying, Marc, and thanks for your attention!

I tried building on 64 bit Windows 7 and Cygwin, and saw the same errors.

I tried the ./configure CC="gcc -m32", but it did not work (probably due to trying to build 32 bit for a 64 bit Cygwin environment).

I have just got back to building on my original 64 bit Windows 8.1 PC, installed Cygwin 32 bit and have built Gambit-C successfully (so GSI runs fine).

I am quite sure by now that there is something specifically nasty about trying to build Gambit-C on  Cygwin64.

Checking the Cygwin User Guide, I see that:
"There's just one important difference. The 64 bit Cygwin compilers use a different data model than the
Mingw and Microsoft compilers. For reference, see the Wikipedia entry on 64-bit computing [http://
en.wikipedia.org/wiki/64-bit_computing#64-bit_data_models].
While the Mingw and Microsoft compilers use the LLP64 data model, Cygwin compilers use the LP64
data model, just like Linux. This affects the size of the type long. In the LLP64 model preferred by
Microsoft, sizeof(long) is 4. This applies for the related Win32 types like LONG, ULONG, DWORD,
etc., too."

Might this have something to do with the problem (which is just an outrageous and fairly uneducated guess on my part)?

**Comment by aking** [comment]
I just installed a fresh cygwin64 environment with the latest Windows10 preview release and I'm seeing the exact same repeated "*** ERROR -- Scheduler reported the exception: #" repeating message when I run gsc.exe or gsi.exe.  Do I really need to remove cygwin64 and replace it with 32bit cygwin?

**Comment by okuoku** [comment]
By `strace` on Cygwin64, REPL on cygwin64 does not want to `select()` on the TTY fd.
Is there any way to disable REPL's TTY handling?
Tested with: f4c4ca340f532788d36d2604bcb5e5d8cb7bc1c6 , Cygwin `2.0.2(0.287/5/3) 2015-05-08 17:00 x86_64`

I don't think Gambit does anything wrong with it though. On Cygwin32,
```
(gdb)
1060        ___disable_heartbeat_interrupts ();
(gdb)
1062        result =
(gdb)
1069        ___enable_heartbeat_interrupts ();
(gdb) p result
$1 = 1
(gdb) p state
$2 = {devs = 0x282808, timeout = 1.7976931348623157e+308,
  relative_timeout = -1.7976931348623157e+308, timeout_reached = 0,
  devs_next = {-1, 0 <repeats 8191 times>}, highest_fd_plus_1 = 4, readfds = {
    fds_bits = {8, 0}}, writefds = {fds_bits = {0, 0}}, exceptfds = {
    fds_bits = {0, 0}}}
```
on Cygwin64,
```
1060        ___disable_heartbeat_interrupts ();
(gdb)
1062        result =
(gdb)
1069        ___enable_heartbeat_interrupts ();
(gdb)
1073        if (result < 0)
(gdb)
1074          return err_code_from_errno ();
(gdb) p result
$1 = -1
(gdb) p state
$2 = {devs = 0x22c4a0, timeout = 1.7976931348623157e+308,
  relative_timeout = -1.7976931348623157e+308, timeout_reached = 0,
  devs_next = {-1, 0 <repeats 8191 times>}, highest_fd_plus_1 = 4, readfds = {
    fds_bits = {8}}, writefds = {fds_bits = {0}}, exceptfds = {fds_bits = {0}}}
```
... pretty much same parameters, different results.

**Comment by okuoku** [comment]
... no, Gambit's configure have a test against ws2_32.lib. DON'T DO THIS. In case we linked against ws2_32.dll, program will use `select()` from Win32 native TCP stack which is obviously incompatible with Cygwin fds.

I'm not sure why do we have check against ws2_32 other than on MinGW... By meantime, remove this line and `autoconf -ifv` then we will get Cygwin64 compatible `configure` script.

```
diff --git a/configure.ac b/configure.ac
index da847ed..42a0f47 100644
--- a/configure.ac
+++ b/configure.ac
@@ -1075,7 +1075,7 @@ else

                AC_SEARCH_LIBS(openpty,util)

-               AC_SEARCH_LIBS(WSAStartup,ws2_32)
+               #AC_SEARCH_LIBS(WSAStartup,ws2_32)

                AC_SEARCH_LIBS(timeBeginPeriod,winmm)
                ;;
```

**Comment by okuoku** [comment]
Just filed #191 for my proposed fix.
